Initial version of the syntax highlighting tutorial.
lite-xl/website-archive pull request #14
Opened 2021-10-24 16:15 UTC by dflock

This is an initial version of a tutorial on creating syntax highlighting plugins for lite-xl.

I'm not quote sure about this part, and I'd like feedback on it:

> Each matching pattern captures the text that it matches - so a given run of text can only match one pattern.
> Patterns are tested in the order that they are written in the syntax definition, so the first match will win.

As well as general feedback and corrections etc...

2021-11-05 00:59 UTC, Guldoman requested changes
This was really needed, thank you.
Some of my comments are just suggestions, so feel free to ignore them.

2021-11-05 00:59 UTC, Guldoman commented on en/tutorials/syntax-highlighting.md
> +### How to create syntax highlighting plugins for lite-xl XL
Use Lite XL as the editor name here.

2021-11-05 00:59 UTC, Guldoman commented on en/tutorials/syntax-highlighting.md
> +Like other plugins, syntax definitions are sources from the following folders, in order:
Typo here? s/sources/sourced/?

2021-11-05 00:59 UTC, Guldoman commented on en/tutorials/syntax-highlighting.md
> +- /usr/share/lite-xl/plugins/
Should we specify that this directory depends on OS and install method?

2021-11-05 00:59 UTC, Guldoman commented on en/tutorials/syntax-highlighting.md
> +So, to create a new syntax definition, you can just create a file in your `~/.config/lite-xl/plugins/` folder.
> you can just create a ***`.lua`*** file in your...

2021-11-05 00:59 UTC, Guldoman commented on en/tutorials/syntax-highlighting.md
> +#### What syntax token types are there?
I don't really like this section. I think that it would be better to have the list of token types, followed by an example of where they're used in other language files.

2021-11-05 00:59 UTC, Guldoman commented on en/tutorials/syntax-highlighting.md
> +-- mod-version:2
`-- mod-version:2 -- lite-xl 2.0`

2021-11-05 00:59 UTC, Guldoman commented on en/tutorials/syntax-highlighting.md
> +The `files` property tells lite-xl which files this syntax should be used for. This is a regular expression that matches against the full path of the file being opened. For example, to match against
This is not a regular expression, it's a Lua pattern.

2021-11-05 00:59 UTC, Guldoman commented on en/tutorials/syntax-highlighting.md
> +In our example, we match against the end of the path rather than the extension, because SSH config files don't have extensions - and we don't want to match all `config` files. We expect the path for
> In our ***original*** example...

To avoid confusion with the example in the line just before.

2021-11-05 00:59 UTC, Guldoman commented on en/tutorials/syntax-highlighting.md
> +This regex matches paths that look like that:
pattern

2021-11-05 00:59 UTC, Guldoman commented on en/tutorials/syntax-highlighting.md
> +Next up is the patterns section.
I'd remove this line.

2021-11-05 00:59 UTC, Guldoman commented on en/tutorials/syntax-highlighting.md
> +Each matching pattern captures the text that it matches - so a given run of text can only match one pattern.
I think that this needs to be rephrased.

2021-11-05 00:59 UTC, Guldoman commented on en/tutorials/syntax-highlighting.md
> +##### Simple Regex
Pattern

2021-11-05 00:59 UTC, Guldoman commented on en/tutorials/syntax-highlighting.md
> +
I'd also add that you can use the `regex` keyword instead of `pattern` to specify an actual regex (PCRE).

2021-11-12 21:36 UTC, dflock commented on en/tutorials/syntax-highlighting.md
> +### How to create syntax highlighting plugins for lite-xl XL
Done, thanks.

2021-11-12 21:36 UTC, dflock commented on en/tutorials/syntax-highlighting.md
> +Like other plugins, syntax definitions are sources from the following folders, in order:
Fixed, thanks.

2021-11-12 21:37 UTC, dflock commented on en/tutorials/syntax-highlighting.md
> +- /usr/share/lite-xl/plugins/
I've updated this to explain this a bit more, borrowing from the Usage docs.

2021-11-12 21:37 UTC, dflock commented on en/tutorials/syntax-highlighting.md
> +So, to create a new syntax definition, you can just create a file in your `~/.config/lite-xl/plugins/` folder.
Fixed, thanks.

2021-11-12 21:37 UTC, dflock commented on en/tutorials/syntax-highlighting.md
> +-- mod-version:2
Fixed, thanks.

2021-11-12 21:38 UTC, dflock commented on en/tutorials/syntax-highlighting.md
> +The `files` property tells lite-xl which files this syntax should be used for. This is a regular expression that matches against the full path of the file being opened. For example, to match against
Sorry about the confusion - I didn't understand the distinction between Lua Patterns & Regular Expressions. I think I've cleaned this up now.

2021-11-12 21:38 UTC, dflock commented on en/tutorials/syntax-highlighting.md
> +Next up is the patterns section.
Done, thanks.

2021-11-12 21:38 UTC, dflock commented on en/tutorials/syntax-highlighting.md
> +In our example, we match against the end of the path rather than the extension, because SSH config files don't have extensions - and we don't want to match all `config` files. We expect the path for
Done, thanks.

2021-11-12 21:39 UTC, dflock commented on en/tutorials/syntax-highlighting.md
> +
Done, thanks.

2021-11-12 21:44 UTC, dflock commented on en/tutorials/syntax-highlighting.md
> +Each matching pattern captures the text that it matches - so a given run of text can only match one pattern.
I'm not sure how to phrase this better. Firstly, is this statement correct? I.e.

> Each matching pattern captures the text that it matches - so a given run of text can only match one pattern.

Is that true? I think so, but I don't _know_, and I haven't spent the time to test/figure it out.

2021-11-12 22:06 UTC, dflock commented on en/tutorials/syntax-highlighting.md
> +#### What syntax token types are there?
Is what I'm saying here true - i.e. there _isn't_ actually a fixed list of token types - it's just whatever is defined in the syntax plugins and color scheme?

2021-11-12 23:03 UTC, Guldoman requested changes
There are a few remaining places where `lite-xl` should be changed to `Lite XL`.

2021-11-12 23:03 UTC, Guldoman commented on en/tutorials/syntax-highlighting.md
> +#### What syntax token types are there?
Yes, you are right, but we have a predefined set of types that is _supported_.
Also someone that is creating a syntax plugin is probably more interested in knowing how these types are used, more than the possibility of creating new ones (that will not work across themes).

2021-11-12 23:03 UTC, Guldoman commented on en/tutorials/syntax-highlighting.md
> +Each matching pattern captures the text that it matches - so a given run of text can only match one pattern.
Yes, once the `tokenizer` decides that a piece of text matches a pattern, it will move on.

2021-11-13 00:02 UTC, dflock commented on en/tutorials/syntax-highlighting.md
> +Each matching pattern captures the text that it matches - so a given run of text can only match one pattern.
OK, I had a go at rewriting this bit.

2021-11-13 00:03 UTC, dflock commented on en/tutorials/syntax-highlighting.md
> +#### What syntax token types are there?
Yeah, I think you are probably correct. I've simplified & rewritten this section.

2021-11-13 00:18 UTC, Guldoman approved these changes
This looks good to me.
@takase1121 I think that this could be merged.

2021-11-13 00:19 UTC, takase1121 commented
Excellent, thank you for your review as I have zero experience in this.

2021-11-13 00:19 UTC, merged