Add German translations
lite-xl/website-archive pull request #39
Opened 2024-02-08 15:20 UTC by xStormyy

Translates every page outside of API documentation to german

2024-02-09 07:02 UTC, takase1121 commented
insane

2024-02-14 06:32 UTC, takase1121 requested changes
Please rebase your changes with the latest master to support the language selector (don't forget to unhide it).

2024-02-14 06:32 UTC, takase1121 commented on locales/de/template.html
> +        <a href='/de'><img class='logo' src='/assets/img/logo.svg'/></a>
Adapt this to use `{{ lang }}` and `{{ path }}` as necessary.

2024-02-14 08:54 UTC, xStormyy commented
i've added the changes. If there's anything I did incorrectly or that I should add, then make sure to tell me

2024-02-14 23:52 UTC, takase1121 commented
> i've added the changes. If there's anything I did incorrectly or that I should add, then make sure to tell me

Can you unhide the language selector in the EN pages as well?

2024-02-24 14:47 UTC, takase1121 commented
right, so one more thing.

Since I don't speak German (and I doubt @Guldoman and @adamharrison can), so we won't be able to maintain this. I was partly hoping you would be able to maintain it when contents get updated in the English site, but this is just a problem with i18n.

If you're fine, we might be putting some kind of banner to warn users that latest documentation can be found in the EN version (by checking modtime or something).

2024-02-24 15:03 UTC, xStormyy commented
> If you're fine, we might be putting some kind of banner to warn users that latest documentation can be found in the EN version (by checking modtime or something)

sure

2024-02-24 15:08 UTC, takase1121 approved these changes

2024-02-24 15:08 UTC, merged